### ISSUE TITLE
Node.js 11 で動かない

### ISSUE THREAD

**Issue by FujiHaruka** [the-labo/the-code#2]
@okunishinishi 
`npm test` も失敗する

**Comment by okunishinishi** [comment]
MacBook-Pro-2:the-code okuni$ npm t

> the-code@4.1.5 test /Users/okuni/Projects/the-code
> mocha



  the-code
    ✓ Should skip
    1) Src1
    ✓ Src2 (99ms)

<--- Last few GCs --->

[19571:0x103800000]    42768 ms: Scavenge 1394.4 (1420.4) -> 1394.2 (1421.4) MB, 3.9 / 0.0 ms  (average mu = 0.111, current mu = 0.060) allocation failure 
[19571:0x103800000]    42775 ms: Scavenge 1395.1 (1421.4) -> 1394.8 (1422.9) MB, 3.5 / 0.0 ms  (average mu = 0.111, current mu = 0.060) allocation failure 
[19571:0x103800000]    42782 ms: Scavenge 1395.6 (1422.9) -> 1395.4 (1423.9) MB, 4.4 / 0.0 ms  (average mu = 0.111, current mu = 0.060) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2b9c8674fb7d]
Security context: 0x39380ac9d9f1 <JSObject>
    1: readToken [0x3938523f8919] [/Users/okuni/Projects/the-code/node_modules/babylon/lib/index.js:~8189] [pc=0x2b9c86a5e714](this=0x39382c6023b1 <_class map = 0x393840d14811>,98)
    2: next [0x39384cfc7869] [/Users/okuni/Projects/the-code/node_modules/babylon/lib/index.js:~913] [pc=0x2b9c86a6bcbd](this=0x39382c6023b1 <_class map = 0x393840d14811>)
    3: ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1000623a3 node::Abort() [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 2: 0x100062c0a node::FatalTryCatch::~FatalTryCatch() [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 3: 0x1001a2227 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 4: 0x1001a21c4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 5: 0x1005a68a2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 6: 0x1005a8dd3 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 7: 0x1005a5308 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 8: 0x1005a34c5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
 9: 0x1005afd6c v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
10: 0x1005afdef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
11: 0x10057efe4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
12: 0x1008314e4 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/okuni/.nvm/versions/node/v11.3.0/bin/node]
13: 0x2b9c8674fb7d 
14: 0x2b9c86a5e714 
15: 0x2b9c86a6bcbd 
16: 0x2b9c86a6f780 
Abort trap: 6

**Comment by okunishinishi** [comment]
babylon -> @babel/parserになったらしい

https://babeljs.io/docs/en/next/babel-parser.html

**Comment by okunishinishi** [comment]
node@11で通った

<img width="994" alt="screenshot 2018-11-29 19 41 15" src="https://user-images.githubusercontent.com/745662/49216587-c95f8500-f40e-11e8-87f7-f4084a30854f.png">
